# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b15c2a3bd3b629a7ab88b35861387fbf91e503a34c37e00b61df48be993bfda56eaf61b1574f09b6752a86543f8cb884953aa14f545d12fb40906f3105dcde3

test:
  secret_key_base: 0d8d3c6992dae499b7605b90daf684a5560c10387f5c94e296cfeb47a8feb3f652d5eb7de00249be980cf32c38b7d9cf789474f94ee41d9d3570e76c33f54ea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
